name: flutter_grocery
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.1+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  app_links: ^6.3.1
  audioplayers: ^6.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.0.5
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  expandable_bottom_sheet: ^1.1.1+1
  firebase_auth: ^5.3.2
  firebase_core: ^3.7.0
  firebase_crashlytics: ^4.1.4
  firebase_messaging: ^15.1.4
  fluro: ^2.0.5
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.4
  flutter_google_places: ^0.3.0
  flutter_inappwebview: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.2.0
  flutter_widget_from_html_core: ^0.15.2
  flutter_xlider: ^3.5.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get_it: ^8.0.2
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.6+2
  google_sign_in: ^6.2.1
  http: ^0.13.6
  image_picker: ^1.1.0
  intl: any
  path_provider: ^2.1.3
  phone_numbers_parser: ^9.0.2
  photo_view: ^0.15.0
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  scroll_to_index: ^3.0.1
  share_plus: ^10.1.2
  shared_preferences: ^2.2.3
  shimmer_animation: ^2.1.0+1
  sign_in_with_apple: ^6.1.0
  simple_speed_dial: ^0.1.7
  syncfusion_flutter_datepicker: ^27.1.58
  universal_html: ^2.2.4
  url_launcher: ^6.2.6
  url_strategy: ^0.3.0
dependency_overrides:
  google_api_headers: ^4.2.5
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/svg/
    - assets/language/
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
